### ISSUE TITLE
High cpu load when creating a new outliner file

### ISSUE THREAD

**Issue by lifehaschanged** [Quorafind/Outliner.MD#10]
After clicking the new outliner file button in the ribbon I got huge cpu lag with many seconds delay and this error in the console:
<img width="393" alt="2024-05-08 14_36_02-outliner-20240508143356 - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/Quorafind/Outliner-View/assets/81463128/87fdd3e5-872b-4e4d-aefc-9bffdfd6aa11">

But after some seconds the new file will open and the cpu spike will go away.

**Comment by Quorafind** [comment]
It is weird. I will look into this soon.
