### ISSUE TITLE
Inline embeds in tables

### ISSUE THREAD

**Issue by VerAn1015** [Quorafind/Outliner.MD#14]
The inline embed feature is such a good addition! Thank you!

However, I ran a problem when using it inside tables. It embeds the entire table instead of just the inline, and it is only seen in live preview. The inline embeds are not seen in reading view. See gif below:

![Obsidian_TF6GgaH3YJ](https://github.com/Quorafind/Outliner-View/assets/148541981/38ff12f0-f0a3-49e4-acf8-8faff21df604)

Is it possible to make it work in tables? Thanks again for this plugin!

**Comment by Quorafind** [comment]
Supported in 0.1.3, but there is some limitation for this feature, it will just show the source rather than live preview of the embedded content.

**Comment by Quorafind** [comment]
Hope this would be tackled in the near future.

**Comment by VerAn1015** [comment]
I just tested it, it works in live preview. Thank you for the quick work @Quorafind! 

Do you mean that it does not work in reading view? Because this is what currently happens. When I edit the source note of the inline embed, the table in the inline embed duplicates in reading view of the other note continuously for every edit I make. See below
![Obsidian_KbBZeS3KfU](https://github.com/Quorafind/Outliner.MD/assets/148541981/79f47d4c-2da1-49bd-89f2-7d8ffe96b21a)
