### ISSUE TITLE
[BUG] Color of title didn't respect the changes of theme

### ISSUE THREAD

**Issue by enneaa** [Quorafind/Outliner.MD#16]
The color is black when toggle dark theme in Obsidian.

在暗黑模式下，标题还是黑色的，没有转换为浅色。

![Screenshot_20240513-213124_Obsidian](https://github.com/Quorafind/Outliner-View/assets/11749618/77da07fa-e00e-4864-a352-e741f8f8af1d)

**Comment by Quorafind** [comment]
在 0.1.2 中已经修复。
