### ISSUE TITLE
[Feature Request] Make inline embedded links clickable 

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Outliner.MD#20]
The `advanced-uri` feature has similar functionality, such as clicking on `[ref](<obsidian://advanced-uri?id=20240405-083908&openmode=popover&block=1nt1q7&search=standardizes the training>)` to open an MD file with the ID 20240405-083908 in a popover window, and using the search function to automatically locate the text "standardizes the training" within the block indexed as 1nt1q7. The effect is as follows:
![image](https://github.com/Quorafind/Outliner.MD/assets/65625632/cbb4aafb-afef-48be-a027-b671ab5731c5)

This idea could potentially be borrowed, for instance, for links like `[[test|o-c234]]`, enabling links named `o-c234` to automatically search and locate the position of `o-c234` within the `test` document after jumping to it, effectively reducing the smallest recognizable granularity from an entire block to any text within a block.

-----

advanced-uri有类似的操作, 比如点击`[ref](<obsidian://advanced-uri?id=20240405-083908&openmode=popover&block=1nt1q7&search=standardizes the training>)`, 即可以浮窗的形式打开id为20240405-083908的md文件, 并通过搜索功能自动定位到索引为1nt1q7的块的内部的standardizes the training文字. 效果如下:
![image](https://github.com/Quorafind/Outliner.MD/assets/65625632/cbb4aafb-afef-48be-a027-b671ab5731c5)

相关思路或许可以借鉴, 比如对于[[test|o-c234]], 使以o-c234为名的链接可以在跳转到test文件后自动搜索定位到o-c234所在位置, 变相使识别的最小粒度从一个完整的块变为块内的任意文字.

**Comment by Quorafind** [comment]
Support in 0.1.3. [doc](https://docs.outliner.md/en-US/editor/copy-link-to-text-fragment)

已经在 0.1.3 中支持。[文档](https://docs.outliner.md/zh-CN/editor/copy-link-to-text-fragment)

**Comment by XMB-7** [comment]
似乎指向文本高亮的代码部分还是没推上去, 我在沙箱里点击链接并不能触发跳转高亮, 无论阅读模式还是编辑模式

![recording](https://github.com/Quorafind/Outliner.MD/assets/65625632/8b45d7da-d767-4d95-bd62-e7bf80ae7325)

**Comment by Quorafind** [comment]
> 似乎指向文本高亮的代码部分还是没推上去, 我在沙箱里点击链接并不能触发跳转高亮, 无论阅读模式还是编辑模式
> 
> ![recording](https://github.com/Quorafind/Outliner.MD/assets/65625632/8b45d7da-d767-4d95-bd62-e7bf80ae7325)
> 

编辑模式下，你最好按住 ctrl 点击它来保证你确实触发了点击

**Comment by XMB-7** [comment]
可能是个bug, 我重启电脑之后, 复现不出来了, 现在不用按ctrl, 正常点链接就能跳转高亮.
又或许插件更新后必须要重启ob? 若是这样最好将之写进文档.

**Comment by Quorafind** [comment]
> 可能是个bug, 我重启电脑之后, 复现不出来了, 现在不用按ctrl, 正常点链接就能跳转高亮.
> 又或许插件更新后必须要重启ob? 若是这样最好将之写进文档.

如果是 bug 的话，后续修复就好。不占据文档的空间，我加在更新文档中。
