### ISSUE TITLE
the block don't show when enable editable block embeds

### ISSUE THREAD

**Issue by thormaxx** [Quorafind/Outliner.MD#23]
when enable  `Editable block embeds`， the block `![[link^block]]` disappeared, but the link is still there, it just doesn't show

**Comment by Quorafind** [comment]
> when enable `Editable block embeds`， the block `![[link^block]]` disappeared, but the link is still there, it just doesn't show

Seems like you are using wrong block id? Could you provide me more information about it? For example, what kind of block are you refer? list block, line block or codeblock block?

And could you try to refer heading block like `![[link#heading1]]` or just `![[link]]` to see if all kinds of embed is not working?

**Comment by thormaxx** [comment]
the real link is `![[@vanderWoerd2023#^8c9752]]`, it shows as follow picture when `Editable block embeds` turn off
![image](https://github.com/Quorafind/Outliner.MD/assets/51023190/e9849be1-e493-4d5f-9447-df1e9d1449c5)

as the button turn on, the content disappeared, but the link is still there

**Comment by Quorafind** [comment]
It's weird. I will look into it soon.

**Comment by Quorafind** [comment]
Could you provide the orignal content you referred?

**Comment by thormaxx** [comment]
Sorry, just see it.

I think it doesn't matter about the content. I try to cite several files again with `![[ ]]`, only `.md` goes wrong, other files can be shown correctly. And, no matter what content in `.md`, the problem occurs

**Comment by Quorafind** [comment]
Could you please try using sandbox vault that enables only outliner.md. And see if this issue remains?

**Comment by thormaxx** [comment]
Ok，I will try it！
but，what is sandbox vault? where can i find it? I searched, but can't find it
i create a new empty vault and enables only outliner.md, the problem still exists

**Comment by Quorafind** [comment]
![image](https://github.com/Quorafind/Outliner.MD/assets/13215013/989982c8-03d3-4a55-ae39-d85bddffa1c5)

Could you provide me details step to repro your issue? And did you update Obsidian to latest version?

For example, details step(maybe there is something different):

1. Create a note A, and then input anything in it.
```markdown
here is what i input
```
2. Create a new  note B, and then trigger block embedded via `[[` 
3. Embed the note A.
4. Done.

**Comment by thormaxx** [comment]
oops。。。。
and。。。it works correctly suddenly。。。
thormaxx
***@***.***
---- Replied Message ----
***@***.***>Date5/17/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [Quorafind/Outliner.MD] the block don't show when enable editable block embeds (Issue #23)
image.png (view on web)
Could you provide me details step to repro your issue? And did you update Obsidian to latest version?
For example, details step(maybe there is something different):
Create a note A, and then input anything in it.
here is what i input
Create a new note B, and then trigger block embedded via [[
Embed the note A.
Done.

**Comment by Quorafind** [comment]
Nice.
