### ISSUE TITLE
Command name is still `Outliner View` in hotkey setting page.

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Outliner.MD#24]
Consequently searching `outliner.md` returns nothing.
![image](https://github.com/Quorafind/Outliner.MD/assets/65625632/4c28b38f-8704-4df5-a08b-ea56b037fac3)

**Comment by Quorafind** [comment]
Please check if there are two `outliner-view` plugins in your plugins folder. Or just check if the version of `outliner.md` is 0.1.2. If not, please uninstall it completely and then reinstall iy again.

**Comment by XMB-7** [comment]
Just found that BRAT keeps both outliner-view and outliner.md installed after plugin renaming.
