### ISSUE TITLE
[Feature Request] Add a command to create a inline link.

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Outliner.MD#25]
Compared to command `creating inline embed`, for example, it would just copy [[test|o-686c]] instead of ![[test|o-686c]] to prevent auto-embedding when pasting the link to text being selected.

**Comment by Quorafind** [comment]
Support in 0.1.3. [doc](https://docs.outliner.md/en-US/editor/copy-link-to-text-fragment)

已经在 0.1.3 中支持。[文档](https://docs.outliner.md/zh-CN/editor/copy-link-to-text-fragment)
