### ISSUE TITLE
[Feature Request] Setting for auto-fold/unfold task group at the bottom of outliner-view

### ISSUE THREAD

**Issue by enneaa** [Quorafind/Outliner.MD#26]
Tasks with the `#now` tag can now automatically appear under the outline view, but they are collapsed by default, making it impossible to see the tasks directly.

It is recommended to adjust them to be expanded by default, which would make handling tasks more convenient.

----

现在#now标签的任务可以自动显示在大纲视图下方，但是现在默认是折叠的，无法直接看到有哪些任务。

建议调整为默认展开，这样可以方便的处理任务。
![Screenshot_20240517-084840_Obsidian](https://github.com/Quorafind/Outliner.MD/assets/11749618/fe8dbe2b-b4ed-408a-8126-9ce76b95ba6e)

**Comment by Quorafind** [comment]
Support in 0.1.3. [doc](https://docs.outliner.md/en-US/outliner-view/task-group#auto-foldunfold)

已经在 0.1.3 中支持。[文档](https://docs.outliner.md/zh-CN/outliner-view/task-group#%E8%87%AA%E5%8A%A8%E5%B1%95%E5%BC%80%E6%88%96%E6%8A%98%E5%8F%A0)
