### ISSUE TITLE
[Feature Request] Style of outliner view

### ISSUE THREAD

**Issue by enneaa** [Quorafind/Outliner.MD#27]
Remove the background of outliner view or consider add setting for this.

现在桌面版大纲视图四周有一圈灰色阴影，割裂感很强。
大纲视图样式建议采用沉浸式设计和原生视图样式保持一致。
我看视频演示里面大纲视图四周没有这一圈灰色阴影的。

![image](https://github.com/Quorafind/Outliner.MD/assets/11749618/5681187f-2321-489f-9aca-fe7ef2a33895)

**Comment by Quorafind** [comment]
已支持设置更改，教程：[doc](https://docs.outliner.md/zh-CN/outliner-view/paper-layout)
