### ISSUE TITLE
[Style] Style of text in outliner view

### ISSUE THREAD

**Issue by enneaa** [Quorafind/Outliner.MD#28]
Text weight of text is bold in outliner view.

Windows 10 桌面版大纲视图文字显示为粗体，应该是bug。

![image](https://github.com/Quorafind/Outliner.MD/assets/11749618/9ae04852-9a96-4474-94df-8bdc2f527ad8)

**Comment by Quorafind** [comment]
这是特意设置。

**Comment by enneaa** [comment]
> 这是特意设置。

只有桌面版是加粗吗，移动版上面我没看出来。
默认加粗的话，如果再给文字加粗怎么区分。

个人感觉默认应该不需要加粗文字。

**Comment by Quorafind** [comment]
类似地，设置也是： [doc](https://docs.outliner.md/zh-CN/outliner-view/paper-layout)
