### ISSUE TITLE
Click on backlink to jump back to match position

### ISSUE THREAD

**Issue by lovedeer1314** [Quorafind/Outliner.MD#29]
Currently, the default behavior is clicking backlink and then jump back to file rather than the matched position.

如题,点击回链之后只能回到文件,而不能跳转到引用的地方,希望能增加支持这个功能

**Comment by Quorafind** [comment]
已支持，教程：[doc](https://docs.outliner.md/zh-CN/editor/backlink-editing#%E8%BF%94%E5%9B%9E)

Supported in 0.1.3，how to: [doc](https://docs.outliner.md/en-US/editor/backlink-editing#jump-back)

**Comment by enneaa** [comment]
咦 没有开启这个插件的时候 点击反链好像也是跳转到链接处

**Comment by Quorafind** [comment]
> 咦 没有开启这个插件的时候 点击反链好像也是跳转到链接处

开启后，如果点击会直接跳转过去就无法编辑反链了，所以需要额外的步骤处理这个逻辑。他提到的是开启该插件以后的改进需求

**Comment by enneaa** [comment]
> > 咦 没有开启这个插件的时候 点击反链好像也是跳转到链接处
> 
> 开启后，如果点击会直接跳转过去就无法编辑反链了，所以需要额外的步骤处理这个逻辑。他提到的是开启该插件以后的改进需求

我刚看了下，如果直接点击反链标题部分，而不是点击反链内容部分，是直接跳转到原文对应链接处，和点击新添加的那个按钮效果是一样的。如果是这样的话新添加的按钮功能和直接点击反链标题功能是重复的。


https://github.com/Quorafind/Outliner.MD/assets/11749618/a0afbf86-962c-45b2-be15-84b56fd72a01
