### ISSUE TITLE
Apply Outliner View to All Mode

### ISSUE THREAD

**Issue by enneaa** [Quorafind/Outliner.MD#31]
现在只有特定属性的笔记才会自动应用大纲视图，在大纲视图实际上也可以容纳不是无序列表的内容。
可否让所有笔记都拥有大纲视图的功能，添加无序列表后让无序列表自动拥有大纲方面的功能，或者把这些功能从列表扩展到所有的内容块。

**Comment by Quorafind** [comment]
未来不会允许非大纲的内容，当前只是技术因素而已。。
