### ISSUE TITLE
[FR] Add a command and option in menu to jump between link and linked text fragment 

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Outliner.MD#34]
Hope to have an option to jump back to where the link locates, after having clicked it to navigate to the target text fragment.
This would help links behave like footnotes.

![image](https://github.com/Quorafind/Outliner.MD/assets/65625632/5c8ac31a-8957-4def-a9a4-3b6b995aef4e)

**Comment by Quorafind** [comment]
Fixed

**Comment by XMB-7** [comment]
抱歉, 可能是我英文水平不行, 没准确表达实际的意思. 新版能够选择复制link还是embedded link当然很棒, 但这不是我所期待的功能请求.

我目前频繁地将该插件用于替代实现脚注的功能, 通过包裹空格指向不同正文位置, 比如:
`aaa... %%o-8789%% %%o-8789%% bbb... %%o-1119%% %%o-1119%% ccc...`
然后我就可以在稍后合适的位置为aaa这一部分正文添加笔记内容: `[[2016|o-8789]]: 这是对aaa的笔记`. 我觉得这种用法极大解决了脚注的痛点, 是该插件对我而言最为重要的功能, 比嵌入任意文本进行实时编辑对我更实用.

我不确定这种用法是否很少人用, 但我觉得这极大提高了我的笔记体验, 甚至改变了我记笔记的方式与我笔记的排版结构. 只不过目前这种用法有一个问题是, 对于`[[2016|o-8789]]: 笔记内容`, 你能一眼看到笔记的具体内容, 但却无法一眼看到它是为什么内容而做的笔记. 此时只好点击链接, 实际跳转到%%o-8789%% %%o-8789%%, 才能知晓原来是对被指向的空格之前的aaa做的笔记, 接着再跳转回来继续往下阅读. 目前插件缺失支持跳转回来的功能, 也就是从%%o-8789%% %%o-8789%%再跳转回[[2016|o-8789]]所在行的功能. 暂时我是使用记忆光标位置历史记录的插件来实现文本的链接与被链接的文本之间的来回跳转的, 但如果能直接支持, 就再好不过了.

此外, 为了能更方便地查看[[2016|o-8789]]所指向的内容, 我还提了一个fr #33, 希望能用鼠标悬浮于链接上额外打开一个浮窗跳转到aaa的所在行, 这样也就不必在当前页实际跳转过去查看了, 而是额外在额外的浮窗里跳转过去查看.
