### ISSUE TITLE
[BUG] broken rendering in second window

### ISSUE THREAD

**Issue by Friedolito** [Quorafind/Outliner.MD#39]
In a second window, the embed rendering doesn't work properly.

The same note is opened in the main and secondewindow:
<img width="2414" alt="Screenshot -2024-05-22 at 11 48 35@2x" src="https://github.com/Quorafind/Outliner.MD/assets/53973194/b5150169-6272-4aa3-9331-012852bdecd3">

outliner.md: Version: 0.1.3
Obsidian: V1.6.0

Thank you for working on it! :)

**Comment by Quorafind** [comment]
Fixed
