### ISSUE TITLE
[FR] Can avoid conflicts between paper layout and plugin banners 2.0.5-beta 

### ISSUE THREAD

**Issue by xiaoxiang01a** [Quorafind/Outliner.MD#41]
when outliner.md and banners2.0.5-beta both open, the paper layout could not extend
![image](https://github.com/Quorafind/Outliner.MD/assets/73389963/2af3d65e-eac1-4e9d-8e52-45a56a3a2ce6)

**Comment by Quorafind** [comment]
Fixed
