### ISSUE TITLE
[Bug] Cannot properly  insert any  image as image  into note when plugin Paste image rename is enabled

### ISSUE THREAD

**Issue by danieltomasz** [Quorafind/Outliner.MD#43]
Here the link to the plugin https://github.com/reorx/obsidian-paste-image-rename
When both paste image and  open md  are enabled in the note and I try to paste image I am getting  the  content of image file not actual image
![image](https://github.com/Quorafind/Outliner.MD/assets/7980381/76624188-ea3b-4c00-ae86-28a8c82a7a74)

**Comment by Quorafind** [comment]
Fixed
