### ISSUE TITLE
[Bug] 在浮动窗口打开的时候出现了大面积的留白

### ISSUE THREAD

**Issue by Moyf** [Quorafind/Outliner.MD#47]
浮动窗口中会拉成很长的一条，并且下面原本笔记的内容也显示错误

![image](https://github.com/Quorafind/Outliner.MD/assets/4013062/345589b0-53e8-4fd8-8e2e-d653f8c6c433)
![image](https://github.com/Quorafind/Outliner.MD/assets/4013062/b6a94cc6-f778-4a85-99c4-c1959bcfcacc)
___

正常情况下应该：
![image](https://github.com/Quorafind/Outliner.MD/assets/4013062/57bf68d0-31ff-483b-97e7-de1d5dcdf088)

**Comment by Moyf** [comment]
补充：和 https://github.com/Quorafind/Outliner.MD/issues/39#issue-2310089675 好像是同一个问题

**Comment by Quorafind** [comment]
重复 #39
