### ISSUE TITLE
Embed to text fragment that contains URL is not working well when using reading mode

### ISSUE THREAD

**Issue by alonexp** [Quorafind/Outliner.MD#49]
Quoted original content:
![image](https://github.com/Quorafind/Outliner.MD/assets/44101833/0b6527a6-fd75-431f-8cd4-9184aa310d2d)

Quoted content after:
![image](https://github.com/Quorafind/Outliner.MD/assets/44101833/ad36f111-1105-4a2e-be3b-6edf8b72d767)

Embedded content (edit mode):
![image](https://github.com/Quorafind/Outliner.MD/assets/44101833/7ec8f792-356d-46a1-b66c-77e0b5725314)
![image](https://github.com/Quorafind/Outliner.MD/assets/44101833/e8c19023-cdab-4839-8eaf-436542d5eec5)

Embedded content (reading mode):
![image](https://github.com/Quorafind/Outliner.MD/assets/44101833/12168c31-2b08-4eba-b4a5-c2764b94f66b)

Not sure if it's an operational error or a bug, looking forward to a fix. Thanks.

**Comment by Quorafind** [comment]
Fixed.
