### ISSUE TITLE
Plugin makes it hard to remove lists

### ISSUE THREAD

**Issue by anareaty** [Quorafind/Outliner.MD#5]
When I am using the outline view OR when I have an embedded file and edit it from the embed (in both outline and normal markdown views), I can write in normal text, not in lists. But if I create a list in it, it becomes very hard to delete it and go back to the normal text. Default Obsidian way - to hit enter twice - does not work and simply deleting an empty bullet does not work too. Selecting a bullet to delete it is also not possible. I figured I can delete the bullet only is it has text and if I put the cursor directly before it, which is not very convenied compared to the normal Obsidian expirience. I think there should be easier way to delete lists, especially for embedded files which may be not intended for the pure outline format.

**Comment by Quorafind** [comment]
If this bullet contains any children?

**Comment by anareaty** [comment]
No, I only tried it with bullets without any children so far.

**Comment by Quorafind** [comment]
Would you mind provide some sample text here? I want to dig into see why. If so, please remove text related to private info.

**Comment by Quorafind** [comment]
@lifehaschanged Thanks for explanation! In the outliner-view (yet the outliner file), this behavior is default. But yes, list should be able to delete when in the embedded editor. Sorry for that!

**Comment by Quorafind** [comment]
Now this should be fixed in 0.1.3. If you still encounter any issues, reply here.

**Comment by Quorafind** [comment]
By default, outliner view doesn't allow no list bullet, so you cant escape list bullet to create a blank line unless you select it and then delete. But I dont recommend you to do this way
