### ISSUE TITLE
Bug: global search shortcut and editing toolbar plugin

### ISSUE THREAD

**Issue by lifehaschanged** [Quorafind/Outliner.MD#51]
I discovered 2 bugs that seem important:

1. Add a shortcut to global search (the search sidebar of obsidian should open)
2. Go in outliner view and press global search shortcut
3. look in console > can't execute global search

Another thing is compatibility with this extension:
https://github.com/PKM-er/obsidian-editing-toolbar

1. In the options of this extension select "Editing toolbar position" to "following"
2. Select some text in the outliner view
3. Popup after text selection doesn't appear

**Comment by Quorafind** [comment]
What is the shortcut you set for global search ?

**Comment by Quorafind** [comment]
Global search function would be fixed in next version

**Comment by Quorafind** [comment]
0.1.5 should fix the global search hotkey issue. Could you try it when you are free?

**Comment by Quorafind** [comment]
It would be possible to provide a button to toggle between editable and view-only modes for search results. However, Outliner.md would not make all search results editable by default.
