### ISSUE TITLE
Editable Block Embeds - Nested list indicator gone?

### ISSUE THREAD

**Issue by mattmaiorana** [Quorafind/Outliner.MD#56]
First, this is absolutely incredible! Great work finally making it possible to edit embeds. 

Everything is working perfectly aside from nested lists - the collapse indicator seems to be gone so there's no way to collapse a list. 

Is this just an issue on my install, a bug, or a limitation of how this is being implemented?

**Comment by globalhuman** [comment]
This is also the behaviour on my install

**Comment by Quorafind** [comment]
Would be fixed.

**Comment by Quorafind** [comment]
fixed.
