### ISSUE TITLE
[Bug] Internal links not displayed properly if note is in Format YYYY-MM-DD

### ISSUE THREAD

**Issue by ruben-sg** [Quorafind/Outliner.MD#63]
I have daily notes that are titled only with the date, e.g. today's note is 2024-07-08. At the top of my daily note, I have a navigation to get to yesterday and tomorrow. Those internal links are working, but not displayed properly since I am using outliner.md. The title shouldn't show at all, just the "gestern" and "morgen". I attached a screenshot. Any idea on why that's happening and how I can prevent it from happening?

![screenshot](https://github.com/Quorafind/Outliner.MD/assets/24955840/dc9a4ac0-567a-4f0f-bce2-478a2d16cc0d)

**Comment by Quorafind** [comment]
It is weird. Would you mind providing me the original text in the screenshot?

**Comment by ruben-sg** [comment]
The actual note is this (I got rid of the Weekly Note-part):
`
[[2024-07-17|< gestern]] | [[2024-07-19| morgen >]]
# About today
`

But the problem is with a note, that is displaying this note:
`
![[2024-07-18]]%%embed%%
`

**Comment by Quorafind** [comment]
Would you mind seeing if the issue remains?
