### ISSUE TITLE
[FR] Add an option to place the `back to full document` button ahead of the first tab.

### ISSUE THREAD

**Issue by XMB-7** [Quorafind/Outliner.MD#65]
Current:
![image](https://github.com/user-attachments/assets/78981ab7-9f9e-4c12-988a-25d405ce72d8)

What expected:
![image](https://github.com/user-attachments/assets/514410b9-4770-47f7-9264-b470b297ea37)

This would be handier for reviewing content before the first section separator, like md properties and so on, meanwhile making more sense on hierarchical structure.

**Comment by Moyf** [comment]
Got the same idea, agree with that

**Comment by Quorafind** [comment]
Done
