### ISSUE TITLE
[Feedback] Section features 

### ISSUE THREAD

**Issue by Moyf** [Quorafind/Outliner.MD#66]
### Sections Creation

1. The text input box for the Rename function should be set to **single-line text**. Otherwise, pressing Enter will insert a blank line, causing the inserted text characters to be invalid.
   ![image](https://github.com/user-attachments/assets/bffaa704-c39f-4e8e-9269-c3929937851d)
   
   (After changing to single-line, pressing Enter should also confirm the action.)

___

2. Currently, the "New Pagination" function seems to only insert at the end of the page by default. This makes it a bit troublesome when modifying some older notes.

   Could you consider adding a command to **insert a new pagination at the current cursor position**?

   Also, I hope that when creating a new pagination, a text box pops up directly to enter the pagination name.
   (Though these can be done using TP scripts, I just wanted to mention it.)

### View Related

1. Similar to issue65, I hope an option can be added to **move the "View Full Page" button to the far left**, making it easier to click.
   
___

2. I hope a setting can be added: **automatically hide the tab bar when there are no pagination symbols**.
   ![image](https://github.com/user-attachments/assets/d1722e51-79d9-4752-ba59-a6aa59b35c37)
   Otherwise, every page will occupy this line of display 0~0.
   
___

3. Currently, pagination characters are directly converted into separators. Could you also display the pagination names simultaneously?
   ![image](https://github.com/user-attachments/assets/62caff91-8315-43ac-b924-e8b3e3b6602b)

### Functional Related
When I am on pagination A (A is activated) and click A again, it automatically switches back to "View Full Page" mode.
   ![image](https://github.com/user-attachments/assets/b01af052-31b1-4986-b895-43fd615355b4)
   
   This means that **clicking the button again while in activation mode = deactivate**.

___

Lastly, I want to praise this new feature. It feels like it fills in something that OB originally couldn't do. It's really, really good! Very practical, love it! 😋

--------

## 创建分页相关

① Rename 功能的文本输入框最好设置成「**单行文本**」，不然回车会输入一个空行，并且导致插入的文本字符失效
![image](https://github.com/user-attachments/assets/bffaa704-c39f-4e8e-9269-c3929937851d)

（改成单行之后应该也能支持回车键确认了）

___

② 目前的「新建分页」好像默认只会在页面最后插入，想对一些老的笔记改造的时候就有点麻烦。

可以考虑增加一个「**在当前光标位置插入新的分页**」的指令？

另，希望新建分页的时候可以直接弹出输入框，输入分页的名称
（不过这些自己用 TP 脚本也可以搞定，就顺嘴一提）

## 视图相关

① 和 issue65 一样，希望可以增加选项把那个 **「浏览全页」的按钮放到最左边的位置**，这样点击起来方便一点

___

② 希望能增加设置：「**无分页符号时自动隐藏标签页栏**」的选项
![image](https://github.com/user-attachments/assets/d1722e51-79d9-4752-ba59-a6aa59b35c37)
不然每个页面都会占用这一行的显示 0~0

___

③ 目前分页字符会直接转成分隔线，能不能同时显示分页的名称？
![image](https://github.com/user-attachments/assets/62caff91-8315-43ac-b924-e8b3e3b6602b)

## 功能相关
当我在分页A（激活A的状态）时，再点击A一次，就自动切换回「浏览全页」的模式
![image](https://github.com/user-attachments/assets/b01af052-31b1-4986-b895-43fd615355b4)

相当于 **在激活模式下再点一次按钮 = 取消激活**

___

最后夸夸这个新功能，感觉又是狠狠补全了 OB 原先做不到的事情，非常非常好！很实用，爱了 😋

**Comment by u2003** [comment]
非常赞同，
1.“目前的「新建分页」好像默认只会在页面最后插入，想对一些老的笔记改造的时候就有点麻烦。

可以考虑增加一个「在当前光标位置插入新的分页」的指令？”。
针对这一点我觉得也可以增加一些交互，比如在每一个section的标签栏上双击，可以触发一个命令菜单，其中包括在当前section后新增section的选项。
另外在整个文章或者分页中也可以在右键菜单加入相应的命令。比如整个文章中可以有在当前处拆分、新建section到末端等命令；聚焦到单个section中时可以有在当前处拆分的命令。

**Comment by Quorafind** [comment]
Mostly supported, unsupported parts are not considered for now

- Double-click to return to full text view.
- Creating new Section pagination supports insertion after the current page, before the current page, at the beginning, and at the end.
- The "View Full Page" icon can be placed on the far left.
- Option to display title near section line. Ref: [doc](https://docs.outliner.md/pages/20240806224545)

**Comment by Moyf** [comment]
> Mostly supported, unsupported parts are not considered for now
> 
> * Double-click to return to full text view.
> * Creating new Section pagination supports insertion after the current page, before the current page, at the beginning, and at the end.
> * The "View Full Page" icon can be placed on the far left.
> * Option to display title near section line. Ref: [doc](https://docs.outliner.md/pages/20240806224545)

Amazing! Thanks for your work! 🎉
