### ISSUE TITLE
[FR] Retain the original "Open Link" button for embedded blocks  

### ISSUE THREAD

**Issue by Moyf** [Quorafind/Outliner.MD#72]
Now, when the editing feature of the embedded block is enabled, the "Link" button is replaced with the "Edit Link Text" function. 
![image](https://github.com/user-attachments/assets/639fe8fd-c864-45f6-851c-f48297dc0df6)  

Could a button be added to retain the original "Open Link" function?  
![image](https://github.com/user-attachments/assets/5000368f-c061-485d-b384-fc567093442e)  

(If added, the icon could also be changed to keep the "Link" icon consistent with the original button function.)

___

# 给嵌入块保留原来的「打开链接」按钮

现在当开启嵌入块的编辑功能后，「链接」按钮会被替换成「编辑链接文本 」的功能。
![image](https://github.com/user-attachments/assets/639fe8fd-c864-45f6-851c-f48297dc0df6)

可否添加一个按钮，保留原来的「打开链接」功能？
![image](https://github.com/user-attachments/assets/5000368f-c061-485d-b384-fc567093442e)

（如果添加的话，图标也可以换一下，让“链接”图标和原本的按钮功能保持一致）

**Comment by Quorafind** [comment]
Will support press ctrl key to open file rather than create a new button for this.

会支持按住 ctrl 来打开文件而不是创建一个新的按钮

**Comment by Moyf** [comment]
> Will support press ctrl key to open file rather than create a new button for this.
> 
> 会支持按住 ctrl 来打开文件而不是创建一个新的按钮

Great!
好嘞，也没问题！

**Comment by Quorafind** [comment]
Fixed.
