### ISSUE TITLE
这个插件功能有点多，是否可以让里面的各功能单独成为插件，感觉很多功能我并不需要

### ISSUE THREAD

**Issue by jiajiala** [Quorafind/Outliner.MD#83]
插件的反向链接渲染真的好棒，但是其他功能感觉我不是很需要
感觉outliner.md像很多插件聚合在一起

**Comment by Quorafind** [comment]
这是一个解决方案类型插件，所以所有用户或我用得上的功能都在里面。后边会提供各个功能的开关选项的，但是应该不会考虑拆分
