### ISSUE TITLE
Missing note title inside an embedded link

### ISSUE THREAD

**Issue by lifehaschanged** [Quorafind/Outliner.MD#9]
Missing note title inside an embedded link:
<img width="320" alt="2024-05-08 14_45_02-2024-05-08 14_44_41-outliner-20240508143356 - Obsidian Sandbox - Obsidian v1 5 1" src="https://github.com/Quorafind/Outliner-View/assets/81463128/a282097b-8647-49e3-8ca8-9de3ab5e7361">

Here the visible title ("Heading")in an embedded note when the plugin is disabled:
<img width="310" alt="2024-05-08 17_06_30-yess - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/Quorafind/Outliner-View/assets/81463128/f7ab8fe8-2e13-49be-956f-a102968da705">

**Comment by Quorafind** [comment]
Because the content in the embed file is editable. It would be confused that show a title that is not editable

**Comment by Quorafind** [comment]
Hello, now i found that is not easy to do it so that I decide to only support click to back and highlight the `![[asdasd]]` content. Do you feel it good?

**Comment by Quorafind** [comment]
It is weird. I didn't remember that I controled the behavior.

**Comment by Quorafind** [comment]
Fixed issue that fold cannot hide embedded content in 0.1.2
